Repository Core-Foreign-Employee-Hiring/Back-end, pull requests merged in 2025-02, with the labels that each got.

#75 [FIX] 고용인 마이페이지 내 공고 수정.
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/MyDraftRecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/MyRecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepository.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepositoryImpl.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepositoryQueryDSL.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
Labels: FIX, 용범

#77 [FIX] 공고 모집 인원 관리 기능 삭제로 인한 기존 코드 수정
  src/main/java/com/core/foreign/api/recruit/dto/RecruitDetailResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/GeneralRecruit.java
  src/main/java/com/core/foreign/api/recruit/entity/PremiumRecruit.java
  src/main/java/com/core/foreign/api/recruit/entity/Recruit.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
Labels: FIX, 용범

#79 [FEAT] 평가하기 기능 개발.
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/dto/EmployeeEvaluationCountDTO.java
  src/main/java/com/core/foreign/api/member/dto/EmployeeToEmployerEvaluationRequestDTO.java
  src/main/java/com/core/foreign/api/member/dto/EmployerEvaluationCountDTO.java
  src/main/java/com/core/foreign/api/member/dto/EmployerToEmployeeEvaluationRequestDTO.java
  src/main/java/com/core/foreign/api/member/entity/EmployeeEvaluation.java
  src/main/java/com/core/foreign/api/member/entity/EmployeeEvaluationId.java
  src/main/java/com/core/foreign/api/member/entity/EmployerEvaluation.java
  src/main/java/com/core/foreign/api/member/entity/EmployerEvaluationId.java
  src/main/java/com/core/foreign/api/member/entity/Evaluation.java
  src/main/java/com/core/foreign/api/member/entity/EvaluationCategory.java
  src/main/java/com/core/foreign/api/member/entity/EvaluationType.java
  src/main/java/com/core/foreign/api/member/entity/ResumeEvaluation.java
  src/main/java/com/core/foreign/api/member/entity/ResumeEvaluationId.java
  src/main/java/com/core/foreign/api/member/repository/EmployeeEvaluationRepository.java
  src/main/java/com/core/foreign/api/member/repository/EmployerEvaluationRepository.java
  src/main/java/com/core/foreign/api/member/repository/EvaluationRepository.java
  src/main/java/com/core/foreign/api/member/repository/ResumeEvaluationRepository.java
  src/main/java/com/core/foreign/api/member/service/EvaluationCreator.java
  src/main/java/com/core/foreign/api/member/service/EvaluationReader.java
  src/main/java/com/core/foreign/api/member/service/EvaluationService.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitDetailResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitmentApplyStatusDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/Resume.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryQueryDSL.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/initializer/EvaluationDataLoader.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FEAT, 용범

#81 [FEAT] 포트폴리오 기능 개발
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/dto/EmployeeBasicResumeResponseDTO.java
  src/main/java/com/core/foreign/api/member/dto/EmployeeEvaluationCountDTO.java
  src/main/java/com/core/foreign/api/member/dto/EmployeePortfolioDTO.java
  src/main/java/com/core/foreign/api/member/dto/TagResponseDTO.java
  src/main/java/com/core/foreign/api/member/entity/Employee.java
  src/main/java/com/core/foreign/api/member/entity/Member.java
  src/main/java/com/core/foreign/api/member/repository/EmployeeEvaluationRepository.java
  src/main/java/com/core/foreign/api/member/repository/EmployeePortfolioRepository.java
  src/main/java/com/core/foreign/api/member/repository/EmployeeRepository.java
  src/main/java/com/core/foreign/api/member/repository/MemberRepository.java
  src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java
  src/main/java/com/core/foreign/api/member/service/EvaluationReader.java
  src/main/java/com/core/foreign/api/member/service/EvaluationService.java
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/portfolio/dto/ApplicationPortfolioPreviewResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/ApplicationPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/BasicPortfolioPreviewResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/BasicPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumePreviewResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/PremiumResumeRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/Resume.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryQueryDSL.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FEAT, 용범

#83 [FEAT] 알바 후기 댓글 등록 기능 구현
  src/main/java/com/core/foreign/api/albareview/controller/AlbaReviewCommentController.java
  src/main/java/com/core/foreign/api/albareview/dto/AlbaReviewCommentCreateDTO.java
  src/main/java/com/core/foreign/api/albareview/dto/AlbaReviewCommentResponseDTO.java
  src/main/java/com/core/foreign/api/albareview/dto/AlbaReviewCreateDTO.java
  src/main/java/com/core/foreign/api/albareview/entity/AlbaReviewComment.java
  src/main/java/com/core/foreign/api/albareview/repository/AlbaReviewCommentRepository.java
  src/main/java/com/core/foreign/api/albareview/repository/AlbaReviewRepository.java
  src/main/java/com/core/foreign/api/albareview/service/AlbaReviewCommentService.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/Portfolio.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/common/config/security/SecurityConfig.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FEAT, 태근

#84 [FIX] 화면 정의서 수정에 따른 포트폴리오 부분 수정.
  src/main/java/com/core/foreign/api/business_field/BusinessFieldTarget.java
  src/main/java/com/core/foreign/api/business_field/entity/BusinessFieldEntity.java
  src/main/java/com/core/foreign/api/business_field/entity/EmployerBusinessField.java
  src/main/java/com/core/foreign/api/business_field/entity/EmployerBusinessFieldId.java
  src/main/java/com/core/foreign/api/business_field/repository/BusinessFieldEntityRepository.java
  src/main/java/com/core/foreign/api/business_field/repository/EmployerBusinessFieldRepository.java
  src/main/java/com/core/foreign/api/business_field/service/BusinessFieldUpdater.java
  src/main/java/com/core/foreign/api/member/controller/AuthController.java
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/dto/EmployeePortfolioDTO.java
  src/main/java/com/core/foreign/api/member/entity/Employee.java
  src/main/java/com/core/foreign/api/member/entity/Employer.java
  src/main/java/com/core/foreign/api/member/entity/Member.java
  src/main/java/com/core/foreign/api/member/repository/EmployeePortfolioRepository.java
  src/main/java/com/core/foreign/api/member/repository/EmployeeRepository.java
  src/main/java/com/core/foreign/api/member/service/EmailService.java
  src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/portfolio/dto/BasicPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/EmployeeApplicationStatusResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/PortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/ResumePortfolio.java
  src/main/java/com/core/foreign/api/recruit/repository/PortfolioRepository.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/initializer/BusinessFieldDataLoader.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FIX, 용범

#92 [FEAT] 서버 오류, 알림 슬랙 전송 기능 구현
  src/main/java/com/core/foreign/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/core/foreign/common/slack/SlackNotificationService.java
Labels: FEAT, 태근

#90 [FEAT] 알바 후기 댓글 수정, 삭제 기능 구현
  src/main/java/com/core/foreign/api/albareview/controller/AlbaReviewCommentController.java
  src/main/java/com/core/foreign/api/albareview/dto/AlbaReviewCommentResponseDTO.java
  src/main/java/com/core/foreign/api/albareview/dto/AlbaReviewCommentUpdateDTO.java
  src/main/java/com/core/foreign/api/albareview/repository/AlbaReviewRepository.java
  src/main/java/com/core/foreign/api/albareview/service/AlbaReviewCommentService.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FEAT, 태근

#93 [FEAT] 마이페이지 근로 계약서 조회.
  src/main/java/com/core/foreign/api/contract/controller/ContractController.java
  src/main/java/com/core/foreign/api/contract/dto/ContractPreviewResponseDTO.java
  src/main/java/com/core/foreign/api/contract/dto/EmployeeCompletedContractResponseDTO.java
  src/main/java/com/core/foreign/api/contract/dto/EmployerCompletedContractResponseDTO.java
  src/main/java/com/core/foreign/api/contract/entity/ContractMetadata.java
  src/main/java/com/core/foreign/api/contract/repository/ContractMetadataRepository.java
  src/main/java/com/core/foreign/api/contract/service/ContractCreator.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/contract/service/ContractUpdater.java
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitPreviewInContractResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/Resume.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FEAT, 용범

#96 [FIX] 예외 처리 테스트
  src/main/java/com/core/foreign/api/contract/controller/ContractController.java
  src/main/java/com/core/foreign/api/contract/dto/ContractPreviewResponseDTO.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/file/FileDirAndName.java
  src/main/java/com/core/foreign/api/file/controller/FileController.java
  src/main/java/com/core/foreign/api/member/repository/EmployeePortfolioRepository.java
  src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/portfolio/dto/ApplicationPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumePreviewResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/MyDraftRecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/MyRecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioTextResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepository.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
Labels: FIX, 용범

#99 [FIX] 계약서 부분 수정.
  src/main/java/com/core/foreign/api/contract/controller/ContractController.java
  src/main/java/com/core/foreign/api/contract/dto/EmployeeCompletedContractResponseDTO.java
  src/main/java/com/core/foreign/api/contract/entity/Contract.java
  src/main/java/com/core/foreign/api/contract/entity/ContractMetadata.java
  src/main/java/com/core/foreign/api/contract/entity/FileUploadContract.java
  src/main/java/com/core/foreign/api/contract/repository/ContractMetadataRepository.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/contract/service/ContractUpdater.java
  src/main/java/com/core/foreign/api/contract/service/ContractUtils.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
Labels: FIX, 용범

#101 [FIX] 스웨거 문구 수정
  src/main/java/com/core/foreign/common/config/swagger/SwaggerConfig.java
Labels: FIX, 태근

#105 [FIX] 페이지 응답 불필요한 부분 제거.
  src/main/java/com/core/foreign/api/contract/controller/ContractController.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/payment/controller/PaymentController.java
  src/main/java/com/core/foreign/api/payment/service/PaymentService.java
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
Labels: FIX, 용범

#107 [FIX] 프리미엄 공고 포트폴리오 null 처리 로직 추가
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
Labels: FIX, 태근

#109 [FIX] 계약서와 찜하기 부분 수정.
  src/main/java/com/core/foreign/api/contract/controller/ContractController.java
  src/main/java/com/core/foreign/api/contract/dto/AdminContractPreviewResponseDTO.java
  src/main/java/com/core/foreign/api/contract/entity/ContractMetadata.java
  src/main/java/com/core/foreign/api/contract/entity/FileUploadContract.java
  src/main/java/com/core/foreign/api/contract/repository/ContractMetadataRepository.java
  src/main/java/com/core/foreign/api/contract/service/ContractReader.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/contract/service/ContractUpdater.java
  src/main/java/com/core/foreign/api/contract/service/ContractUtils.java
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/dto/EmployerCompanyInfoResponseDTO.java
  src/main/java/com/core/foreign/api/member/entity/Employer.java
  src/main/java/com/core/foreign/api/member/entity/EmployerEmployee.java
  src/main/java/com/core/foreign/api/member/entity/EmployerResume.java
  src/main/java/com/core/foreign/api/member/repository/EmployeeRepository.java
  src/main/java/com/core/foreign/api/member/repository/EmployerEmployeeRepository.java
  src/main/java/com/core/foreign/api/member/repository/EmployerResumeRepository.java
  src/main/java/com/core/foreign/api/member/repository/MemberRepository.java
  src/main/java/com/core/foreign/api/member/service/EvaluationService.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/entity/Resume.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
Labels: FIX, 용범

#112 [FIX] 공고 임시저장 데이터 처리 로직 수정
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/MyDraftRecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/GeneralRecruit.java
  src/main/java/com/core/foreign/api/recruit/entity/PremiumRecruit.java
  src/main/java/com/core/foreign/api/recruit/entity/Recruit.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepository.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
Labels: FIX, 태근

#113 [FIX] 고용인 지원 현황 조회 시 size 추가 및 쿼리 대소문자 구분.
  src/main/java/com/core/foreign/api/contract/controller/ContractController.java
  src/main/java/com/core/foreign/api/contract/service/ContractReader.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/payment/controller/PaymentController.java
  src/main/java/com/core/foreign/api/payment/service/PaymentService.java
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
Labels: FIX, 용범

#115 [REFAC] 슬랙 웹훅 임시 중지
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/core/foreign/common/slack/SlackNotificationService.java
Labels: REFAC, 태근

#117 [FIX] queryDSL null 처리 추가.
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
Labels: FIX, 용범

#119 [FIX] 고용인 완료된 계약서 조회 디자인 화면으로 수정.
  src/main/java/com/core/foreign/api/contract/dto/EmployerCompletedContractResponseDTO.java
Labels: FIX, 용범

#121 [FEAT] 완료된 계약서 상세 조회.
  src/main/java/com/core/foreign/api/contract/dto/EmployeeCompletedContractResponseDTO.java
  src/main/java/com/core/foreign/api/contract/dto/EmployerCompletedContractResponseDTO.java
  src/main/java/com/core/foreign/api/contract/service/ContractReader.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
Labels: FEAT, 용범
