Repository Core-Foreign-Employee-Hiring/Back-end, pull requests merged in 2025-03, with the labels that each got.

#124 [FEAT] 포트폴리오 실제 지원 필터링 구현.
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryQueryDSL.java
Labels: FEAT, 용범

#126 [FIX] 포트폴리오 조회수 추가
  src/main/java/com/core/foreign/api/member/entity/Employee.java
  src/main/java/com/core/foreign/api/member/repository/EmployeeRepository.java
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/portfolio/dto/ApplicationPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/BasicPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/Resume.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
Labels: FIX, 용범

#127 [FEAT] 메인 검색 기능 구현
  build.gradle
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepositoryImpl.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepositoryQueryDSL.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/common/config/security/SecurityConfig.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FEAT, 태근

#129 [FIX] 공고 지원 시 모집 승인 날짜 수정.
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
Labels: FIX, 용범

#131 [FIX] 실제 지원 포트폴리오 조회 시 필터 수정.
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
Labels: FIX, 용범

#133 [FIX] 쿼리 출력 의존성 추가.
  build.gradle
Labels: FIX, 용범

#135 [FIX] 쿼리 실행 전 로그 추가.
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
Labels: FIX, 용범

#137 [FIX] 동적 검색 뻥튀기 문제 해결
  src/main/java/com/core/foreign/api/recruit/service/RecruitSpecifications.java
Labels: FIX, 태근

#139 [FIX] 포트폴리오 조회 시 찜 유무 추가.
  src/main/java/com/core/foreign/api/member/repository/EmployerEmployeeRepository.java
  src/main/java/com/core/foreign/api/member/repository/EmployerResumeRepository.java
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/portfolio/dto/ApplicationPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/BasicPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
Labels: FIX, 용범

#141 [FIX] 고용인 가입 시 개인 주소랑 회사 주소 같음.
  src/main/java/com/core/foreign/api/member/entity/Employer.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
Labels: FIX, 용범

#146 [FEAT] 고용인신뢰도 계산 및 지연 현황 일부 기능 개발
  src/main/java/com/core/foreign/api/member/dto/EmployerReliabilityDTO.java
  src/main/java/com/core/foreign/api/member/repository/EmployerRepository.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitmentApplyStatusDTO.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepository.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
Labels: FEAT, 용범

#148 [FIX] 공고 상세 조회 시 고용인 신뢰도 추가 및 공고 미리 보기
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitDetailResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitPreviewInContractResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitPreviewResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
Labels: FIX, 용범

#149 [FIX] 동적 필터링 로직 간소화
  src/main/java/com/core/foreign/api/recruit/service/RecruitSpecifications.java
Labels: FIX, 태근

#151 [FIX] 포트폴리오 로직 수정.
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/dto/EmployeePortfolioDTO.java
  src/main/java/com/core/foreign/api/member/entity/EmployerResume.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/portfolio/dto/internal/BasicPortfolioDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/response/ApplicationPortfolioPreviewResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/response/ApplicationPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/response/BasicPortfolioPreviewResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/response/BasicPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioReader.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioDTO.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
Labels: FIX, 용범

#153 [REFAC] 프론트 cors 허용
  src/main/java/com/core/foreign/common/config/security/SecurityConfig.java
Labels: REFAC, 용범

#155 [FIX] 로그인 시 회원 이름과 id 반환.
  src/main/java/com/core/foreign/api/member/dto/MemberLoginResponseDTO.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
Labels: FIX, 용범

#157 [FEAT] 회원 탈퇴하기.
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/entity/Employer.java
  src/main/java/com/core/foreign/api/member/entity/Member.java
  src/main/java/com/core/foreign/api/member/repository/EmployeeRepository.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/recruit/entity/Recruit.java
  src/main/java/com/core/foreign/api/recruit/entity/Resume.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepository.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryQueryDSL.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitDeleter.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeDeleter.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FEAT, 용범

#159 [FIX] 공고 조회 급여 필터 리스트화
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitSearchConditionDTO.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitSpecifications.java
Labels: FIX, 태근

#161 [FIX] 공고 상세 조회 시 모집 인원 및 찜하기 상태 추가.
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitDetailResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/GeneralRecruit.java
  src/main/java/com/core/foreign/api/recruit/entity/PremiumRecruit.java
  src/main/java/com/core/foreign/api/recruit/entity/Recruit.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitBookmarkRepository.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
Labels: FIX, 용범

#163 [FIX] 포트폴리오 조회 시 로그인 유무에 따라 다르게 처리.
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/dto/EmployeePortfolioDTO.java
  src/main/java/com/core/foreign/api/member/entity/EmployerEmployee.java
  src/main/java/com/core/foreign/api/member/repository/EmployeePortfolioRepository.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/MyResumeResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/PremiumResumeRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/internal/ResumeDTO.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/config/security/SecurityConfig.java
Labels: FIX, 용범

#165 [FIX] 공고 미리보기 추가된 데이터 추가.
  src/main/java/com/core/foreign/api/recruit/dto/RecruitPreviewResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
Labels: FIX, 용범

#167 [FIX] 프리미엄 공고 이력서만 포트폴리오에 표시
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
Labels: FIX, 용범

#169 [FIX] 피고용인 englishTestScore, englishTestType 제거
  src/main/java/com/core/foreign/api/member/dto/EmployeePortfolioDTO.java
  src/main/java/com/core/foreign/api/member/entity/EmployeePortfolio.java
  src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java
  src/main/java/com/core/foreign/api/portfolio/dto/internal/BasicPortfolioDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/MyResumeResponseDTO.java
Labels: FIX, 용범

#172 [FIX] 파일 업로드 엔드포인트 간소화
  src/main/java/com/core/foreign/api/aws/service/S3Service.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/file/FileDirAndName.java
  src/main/java/com/core/foreign/api/file/controller/FileController.java
  src/main/java/com/core/foreign/api/file/service/FileService.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FIX, 태근

#173 [FIX] 피고용인 포트폴리오 임시 저장 부분 삭제
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/dto/EmployeePortfolioDTO.java
  src/main/java/com/core/foreign/api/member/entity/EmployeePortfolio.java
  src/main/java/com/core/foreign/api/member/entity/EmployeePortfolioStatus.java
  src/main/java/com/core/foreign/api/member/entity/Topik.java
  src/main/java/com/core/foreign/api/member/repository/EmployeePortfolioRepository.java
  src/main/java/com/core/foreign/api/member/repository/ResumeEvaluationRepository.java
  src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/portfolio/dto/internal/BasicPortfolioDTO.java
  src/main/java/com/core/foreign/api/portfolio/dto/response/BasicPortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioReader.java
  src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/MyResumeResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
Labels: FIX, 용범

#175 [FIX] 포트폴리오 조회 시 없을 경우 예외 처리.
  src/main/java/com/core/foreign/api/member/repository/EmployeePortfolioRepository.java
  src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
Labels: FIX, 용범

#177 [FIX] 프리미엄 공고 지원 dto 수정
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/PortfolioResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/PremiumResumeRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioRequestDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/internal/ResumeDTO.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
Labels: FIX, 용범

#181 [FIX] 파일 업로드, 파일 업로드 계약서 등록 및 수정 그리고 피고용인 공고 지원 가능성 판단.
  src/main/java/com/core/foreign/api/contract/controller/ContractController.java
  src/main/java/com/core/foreign/api/contract/entity/ContractMetadata.java
  src/main/java/com/core/foreign/api/contract/entity/FileUploadContract.java
  src/main/java/com/core/foreign/api/contract/entity/FileUploadContractUrl.java
  src/main/java/com/core/foreign/api/contract/repository/FileUploadContractUrlRepository.java
  src/main/java/com/core/foreign/api/contract/service/ContractReader.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/contract/service/ContractUpdater.java
  src/main/java/com/core/foreign/api/file/dto/FileUrlAndOriginalFileNameDTO.java
  src/main/java/com/core/foreign/api/file/dto/request/Urls.java
  src/main/java/com/core/foreign/api/file/entity/UploadFile.java
  src/main/java/com/core/foreign/api/file/repository/UploadFileRepository.java
  src/main/java/com/core/foreign/api/file/service/FileService.java
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioFileResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioTextResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
  src/main/java/com/core/foreign/common/response/SuccessStatus.java
Labels: FIX, 용범

#182 [FIX] 화면 정의서와 디자인 페이지 비교 후 DTO 수정 및 에러 코드 수정
  src/main/java/com/core/foreign/api/contract/service/ContractReader.java
  src/main/java/com/core/foreign/api/contract/service/ContractService.java
  src/main/java/com/core/foreign/api/contract/service/ContractUpdater.java
  src/main/java/com/core/foreign/api/contract/service/ContractUtils.java
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/service/EmailService.java
  src/main/java/com/core/foreign/api/member/service/EvaluationService.java
  src/main/java/com/core/foreign/api/member/service/MemberService.java
  src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
  src/main/java/com/core/foreign/api/recruit/dto/MyDraftRecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/MyRecruitResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitmentApplyStatusDTO.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepositoryImpl.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
Labels: FIX, 용범

#186 [FIX] 평가 취소 시 이력서 상태 변경
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/member/service/EvaluationReader.java
  src/main/java/com/core/foreign/api/member/service/EvaluationService.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/dto/RecruitDetailResponseDTO.java
  src/main/java/com/core/foreign/api/recruit/entity/Resume.java
  src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
Labels: FIX, 용범

#187 [REFAC] 스웨거 정보 변경
  src/main/java/com/core/foreign/api/albareview/controller/AlbaReviewCommentController.java
  src/main/java/com/core/foreign/api/albareview/controller/AlbaReviewController.java
  src/main/java/com/core/foreign/api/contract/controller/ContractController.java
  src/main/java/com/core/foreign/api/file/controller/FileController.java
  src/main/java/com/core/foreign/api/member/controller/AuthController.java
  src/main/java/com/core/foreign/api/member/controller/MemberController.java
  src/main/java/com/core/foreign/api/payment/controller/PaymentController.java
  src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
Labels: REFAC, 태근

#189 [FIX] 공고 지원 시 지원 방법 예외 처리 추가.
  src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java
  src/main/java/com/core/foreign/api/recruit/repository/RecruitRepository.java
  src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
  src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
  src/main/java/com/core/foreign/common/response/ErrorStatus.java
Labels: FIX, 용범
